# Generated by Django 4.1 on 2023-05-03 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                ("prove", models.CharField(max_length=500)),
                ("slug", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("tel", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50)),
                ("emai", models.EmailField(max_length=254)),
                ("Pswd", models.CharField(max_length=30)),
                ("Language", models.CharField(max_length=50)),
                ("HourFormat", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Modele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_minimum", models.IntegerField()),
                ("airbag", models.CharField(max_length=50)),
                ("capacitie", models.FloatField()),
                ("attach_cat", models.CharField(max_length=40)),
                ("clim", models.BooleanField()),
                ("denomination", models.IntegerField()),
                ("marque", models.CharField(max_length=40)),
                ("nb_passag", models.IntegerField()),
                ("nb_perms", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("version", models.IntegerField()),
                ("cat", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Voiture1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=1000)),
                ("Daily_rate", models.IntegerField(null=True)),
                ("Bdy", models.CharField(max_length=50)),
                ("Siege", models.IntegerField(null=True)),
                ("Porte", models.IntegerField(null=True)),
                ("Bagage", models.IntegerField(null=True)),
                ("Carburants", models.CharField(max_length=50)),
                ("Moteur", models.IntegerField(null=True)),
                ("Anne", models.IntegerField(null=True)),
                ("Kilometrage", models.IntegerField(null=True)),
                ("transmission", models.CharField(max_length=50)),
                ("dure", models.CharField(max_length=50)),
                ("Fueleco", models.FloatField(null=True)),
                ("color_exterieur", models.CharField(max_length=50)),
                ("color_inter", models.CharField(max_length=50)),
                ("photo1", models.ImageField(upload_to="")),
                ("photo2", models.ImageField(upload_to="")),
                ("photo3", models.ImageField(upload_to="")),
                ("photo4", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50)),
                (
                    "Agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.agence",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.modele",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lieu_A", models.CharField(max_length=60)),
                ("lieu_B", models.CharField(max_length=60)),
                (
                    "dateA",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "dateB",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.client1",
                    ),
                ),
                (
                    "v",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.voiture1",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateStart",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "dateEnd",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("tarif", models.CharField(max_length=50)),
                ("statusPayment", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.client",
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.voiture",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="car",
            field=models.ManyToManyField(
                through="myappvoiture.Reservation", to="myappvoiture.voiture"
            ),
        ),
    ]
