# Generated by Django 4.1 on 2023-05-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myappvoiture", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation1",
            old_name="v",
            new_name="voiture",
        ),
    ]
