# Generated by Django 4.1 on 2023-05-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappvoiture", "0002_rename_v_reservation1_voiture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiture1",
            name="Daily_rate",
            field=models.IntegerField(default=0),
        ),
    ]
