# Generated by Django 4.1 on 2023-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappvoiture", "0003_alter_voiture1_daily_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiture1",
            name="BL",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="voiture1",
            name="CL",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="voiture1",
            name="MP",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="voiture1",
            name="Sunroof",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
