# Generated by Django 4.1 on 2023-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappvoiture", "0005_remove_client1_emai_client1_email_alter_client1_pswd"),
    ]

    operations = [
        migrations.AddField(
            model_name="client1",
            name="Phone",
            field=models.IntegerField(null=True),
        ),
    ]
