# Generated by Django 4.1 on 2023-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappvoiture", "0006_client1_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client1",
            name="HourFormat",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="client1",
            name="Language",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
