# Generated by Django 4.1.7 on 2023-05-05 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappvoiture', '0008_alter_reservation1_datea_alter_reservation1_dateb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation1',
            name='dateA',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservation1',
            name='dateB',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
